OnlineShop/ServiceHost/Pages/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.Pages.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

OnlineShop/ServiceHost/Pages/ViewComponents/MenuViewComponent.cs
using _01_LampshadeQuery;
using _01_OnlineShopQuery.Contracts.ArticleCategory;
using _01_OnlineShopQuery.Contracts.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.Pages.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IProductCategoryQuery _query;
        private readonly IArticleCategoryQuery _articleCategoryQuery;

        public MenuViewComponent(IProductCategoryQuery query,IArticleCategoryQuery articleCategoryQuery)
        {
            _query = query;
            _articleCategoryQuery = articleCategoryQuery;
        }

        public IViewComponentResult Invoke()
        {
            var result = new MenuModel()
            {
                ProductCategories = _query.GetProductCategoryQueryModels(),
                ArticleCategories = _articleCategoryQuery.GetAllArticleCategories()
            };

            return View(result);
        }
    }
}

OnlineShop/ServiceHost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @if (ViewData["Title"] != null)
    {
        <title>@ViewData["Title"] -فروشگاه</title>
    }
    else
    {
        <title>فروشگاه</title>
    }

    <meta name="keywords" content="@ViewData["keywords"]" />
    <meta name="description" content="@ViewData["metaDescription"]" />

    <link href="~/Theme/assets/css/vendors.css" rel="stylesheet" />
    <link href="~/Theme/assets/css/style.css" rel="stylesheet" />
    <link href="~/Theme/assets/css/Custom.css" rel="stylesheet" />

</head>

<body>

    @await Component.InvokeAsync("Menu");

    @RenderBody()

    @await Component.InvokeAsync("Footer");


    <div class="search-overlay" id="search-overlay">
        <a href="javascript:void(0)" class="close-search-overlay" id="close-search-overlay">
            <i class="ion-ios-close-empty"></i>
        </a>
        <div class="search-form">
            <form method="get" asp-page="/Search">
                <input type="search" name="value" id="value" placeholder="هرچه می خواهید در فروشگاه جستجو کنید ...">
                <button type="submit">
                    <i class="ion-android-search"></i>
                </button>
            </form>
        </div>
    </div>


    <div id="scroll-top">
        <span>برو بالا</span><i class="ion-chevron-right"></i><i class="ion-chevron-right"></i>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Theme/assets/js/vendors.js"></script>
    <script src="~/Theme/assets/js/active.js"></script>
    <script src="~/Theme/assets/js/plugins.js"></script>
    <script src="~/Theme/assets/js/custom.js"></script>

    <script>
        $(document).ready(function () {
            updateCart();
        });
    </script>
</body>

</html>