OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Blog/Articles/Create.cshtml.cs
using ArticleManagement.Application.Contracts.Article;
using ArticleManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.AdminPanel.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public CreateArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Blog/Articles/Edit.cshtml.cs
using ArticleManagement.Application.Contracts.Article;
using ArticleManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.AdminPanel.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {

        public EditArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/ProductCategories/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.AdminPanel.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public ProductCategorySearchModel SearchModel;
        private readonly IProductCategoryApplication _application;
        public List<ProductCategoryViewModel> ProductCategories;

        public IndexModel(IProductCategoryApplication application)
        {
            _application = application;
        }

        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _application.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _application.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _application.GetDetails(id);

            return Partial("./Edit", productCategory);
        }

        public JsonResult OnPostEdit(EditProductCategory command)
        {
            var result = _application.Edit(command);

            return new JsonResult(result);
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/ProductPictures/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Application.Contracts.ProductPicture;

namespace ServiceHost.Areas.AdminPanel.Pages.Shop.ProductPictures
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ProductPictureSearchModel SearchModel;
        private readonly IProductPictureApplication _application;
        private readonly IProductApplication _productApplication;
        public List<ProductPictureViewModel> ProductPictures;
        public SelectList Products;

        public IndexModel(IProductPictureApplication application, IProductApplication productApplication)
        {
            _application = application;
            _productApplication = productApplication;
        }

        public void OnGet(ProductPictureSearchModel searchModel)
        {
            Products = new SelectList(_productApplication.GetProducts(), "Id", "Name");
            ProductPictures = _application.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProductPicture {Products = _productApplication.GetProducts()};

            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProductPicture command)
        {
            var result = _application.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productPicture = _application.GetDetails(id);
            productPicture.Products = _productApplication.GetProducts();

            return Partial("./Edit", productPicture);
        }

        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var result = _application.Edit(command);

            return new JsonResult(result);
        }


        public IActionResult OnGetRemove(long id)
        {
            var result = _application.Remove(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetRestore(long id)
        {
            var result = _application.Restore(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.AdminPanel.Pages.Shop.Products
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public ProductSearchModel SearchModel;
        private readonly IProductApplication _application;
        private readonly IProductCategoryApplication _productCategoryApplication;
        public List<ProductViewModel> Products;
        public SelectList ProductCategories;

        public IndexModel(IProductApplication application, IProductCategoryApplication productCategoryApplication)
        {
            _application = application;
            _productCategoryApplication = productCategoryApplication;
        }

        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Products = _application.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProduct {Categories = _productCategoryApplication.GetProductCategories()};

            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProduct command)
        {
            var result = _application.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var product = _application.GetDetails(id);
            product.Categories = _productCategoryApplication.GetProductCategories();

            return Partial("./Edit", product);
        }

        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _application.Edit(command);

            return new JsonResult(result);
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/Sliders/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;
using ShopManagement.Application.Contracts.ProductPicture;
using ShopManagement.Application.Contracts.Slider;

namespace ServiceHost.Areas.AdminPanel.Pages.Shop.Sliders
{
    public class IndexModel : PageModel
    {

        [TempData]
        public string Message { get; set; }
        public List<SliderViewModel> Sliders;

        private readonly ISliderApplication _application;

        public IndexModel(ISliderApplication application)
        {
            _application = application;
        }

        public void OnGet()
        {
            Sliders = _application.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateSlider();

            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateSlider command)
        {
            var result = _application.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var slider = _application.GetDetails(id);

            return Partial("./Edit", slider);
        }

        public JsonResult OnPostEdit(EditSlider command)
        {
            var result = _application.Edit(command);

            return new JsonResult(result);
        }


        public IActionResult OnGetRemove(long id)
        {
            var result = _application.Remove(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetRestore(long id)
        {
            var result = _application.Restore(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/Sliders/Create.cshtml
@model ShopManagement.Application.Contracts.Slider.CreateSlider
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد اسلاید جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">سرتیتر</label>
                    <input type="text" class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Text" class="control-label">متن</label>
                    <input type="text" class="form-control" asp-for="Text">
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>
        </div>>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="BtnText" class="control-label">متن دکمه</label>
                    <input type="text" class="form-control" asp-for="BtnText">
                    <span asp-validation-for="BtnText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-success waves-effect waves-light">ایجاد</button>
    </div>
</form>

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/Sliders/Edit.cshtml
@model ShopManagement.Application.Contracts.Slider.EditSlider
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش اسلاید : @Model.Heading</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان عکس</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Heading" class="control-label">سرتیتر</label>
                    <input type="text" class="form-control" asp-for="Heading">
                    <span asp-validation-for="Heading" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Text" class="control-label">متن</label>
                    <input type="text" class="form-control" asp-for="Text">
                    <span asp-validation-for="Text" class="error"></span>
                </div>
            </div>
        </div>>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="Title">
                    <span asp-validation-for="Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="BtnText" class="control-label">متن دکمه</label>
                    <input type="text" class="form-control" asp-for="BtnText">
                    <span asp-validation-for="BtnText" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Link" class="control-label">لینک</label>
                    <input type="text" class="form-control" asp-for="Link">
                    <span asp-validation-for="Link" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id"/>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-warning waves-effect waves-light">ویرایش</button>
    </div>
</form>

OnlineShop/ServiceHost/Areas/AdminPanel/Pages/Shop/Sliders/Index.cshtml
@page
@model ServiceHost.Areas.AdminPanel.Pages.Shop.Sliders.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت اسلایدها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد اسلاید جدید</a>
        </p>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست اسلایدها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>سرتیتر</th>
                                    <th>عنوان</th>
                                    <th>وضعیت</th>
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Sliders)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/UploadedPictures/@item.Picture" style="width: 100px; height: 110px" />
                                        </td>
                                        <td>@item.Heading</td>
                                        <td>@item.Title</td>
                                        <td class="text-center">
                                            @if (!item.IsRemoved)
                                            {
                                                <i class="fa fa-check fa-2x text-success"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-remove fa-2x text-danger"></i>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning btn-custom waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"> ویرایش </i>
                                            </a>
                                            @if (!item.IsRemoved)
                                            {
                                                <a asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id"
                                                   class="btn btn-danger btn-custom waves-light m-b-5">حذف</a>
                                            }
                                            else
                                            {
                                                <a asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id"
                                                   class="btn btn-success btn-custom waves-light m-b-5">فعال سازی</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}